import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <main className="flex min-h-screen flex-col items-center justify-between p-24">
            <header>
              <form action={''}>
                <input type='search'/>
                <button type='submit' name='search'> Buscar </button>
               
              </form>
            </header>
          {children}
          </main>
      
      </body>
    </html>
  )
}
